version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker-spotifai/Dockerfile
    container_name: app-container
    ports:
      - "3000:3000"  # Frontend (React)
      - "8888:8888"  # Backend (Express)
    env_file:
      - ../app-web/.env  # Cargar las variables de entorno desde app-web
    volumes:
      - ../app-web:/usr/src/app
    depends_on:
      - neo4j
    networks:
      - red-spotify

  neo4j:
    image: neo4j
    container_name: neo4j-container
    ports:
      - "7888:7474"
      - "7999:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    restart: unless-stopped
    networks:
      - red-spotify

  essentia:
    container_name: essentia-container
    build:
      context: ../music-analizer
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    networks:
      - red-spotify

networks:
  red-spotify:
